! r2 - net_b 와 net_c 에 연결
frr defaults traditional
hostname r2
!
interface eth0
 description net_b (r2 - r1)
 ip ospf cost 10
!
interface eth1
 description net_c (r2 - r3)
 ip ospf cost 10
!
router ospf
 ospf router-id 2.2.2.2
 network 0.0.0.0/0 area 0
!
line vty
