! r3 - net_c 와 net_a 에 연결
frr defaults traditional
hostname r3
!
interface eth0
 description net_c (r3 - r2)
 ip ospf cost 10
!
interface eth1
 description net_a (r3 - r1)
 ip ospf cost 10
!
router ospf
 ospf router-id 3.3.3.3
 network 0.0.0.0/0 area 0
!
line vty
