! r1 - net_a 와 net_b 에 연결
frr defaults traditional
hostname r1
!
interface eth0
 description net_a (r1 - r3)
 ip ospf cost 10
!
interface eth1
 description net_b (r1 - r2)
 ip ospf cost 10
!
router ospf
 ospf router-id 1.1.1.1
 network 0.0.0.0/0 area 0
!
line vty
